using Web.Api.Common;
using Web.Api.Common.ValueObjects;

namespace Web.Api.Features.Exams;

// Metadata for one file belonging to an exam. The bytes live in object storage; this row only ever
// names them. A row exists solely for content that has already been written to storage and read
// back to confirm it - see the two-phase upload in
// UploadExamFileContent and AddExamFile.
public sealed class ExamFile : Entity
{
    public Guid Id { get; set; }
    public Guid ExamPackageId { get; set; }
    public FileName FileName { get; set; }
    public ContentType ContentType { get; set; }

    // Key of the stored object. Always generated by the server, never by a caller.
    public ObjectKey ObjectKey { get; set; }

    public long SizeBytes { get; set; }

    // SHA-256 of the content, computed by the server as it was stored.
    public Sha256Hash Sha256 { get; set; }

    public DateTime CreatedAt { get; set; }
}
