// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web.Api.Database;

#nullable disable

namespace Web.Api.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910170634_Add_Submission_ActivityLog")]
    partial class Add_Submission_ActivityLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web.Api.Features.Devices.DeviceCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_credentials");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ix_device_credentials_secret_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_credentials_user_id");

                    b.ToTable("device_credentials", "public");
                });

            modelBuilder.Entity("Web.Api.Features.ExamSessions.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_professor_id");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("ExamPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_package_id");

                    b.Property<string>("HeaderObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("header_object_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("OneTimeCodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("one_time_code_hash")
                        .IsFixedLength();

                    b.Property<string>("PackageObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("package_object_key");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("package_sha256")
                        .IsFixedLength();

                    b.Property<long>("PackageSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("package_size_bytes");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_sessions");

                    b.HasIndex("CreatedByProfessorId")
                        .HasDatabaseName("ix_exam_sessions_created_by_professor_id");

                    b.HasIndex("OneTimeCodeHash")
                        .HasDatabaseName("ix_exam_sessions_one_time_code_hash");

                    b.HasIndex("PackageObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_sessions_package_object_key");

                    b.HasIndex("ExamPackageId", "StartsAt")
                        .HasDatabaseName("ix_exam_sessions_exam_package_id_starts_at");

                    b.ToTable("exam_sessions", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Exams.ExamDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExamPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_package_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_exam_dependencies");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_dependencies_object_key");

                    b.HasIndex("ExamPackageId", "Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_dependencies_exam_package_id_name_version");

                    b.ToTable("exam_dependencies", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Exams.ExamFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExamPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_package_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("pk_exam_files");

                    b.HasIndex("ExamPackageId")
                        .HasDatabaseName("ix_exam_files_exam_package_id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_files_object_key");

                    b.ToTable("exam_files", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Exams.ExamPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OwnerProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_professor_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exam_packages");

                    b.HasIndex("OwnerProfessorId")
                        .HasDatabaseName("ix_exam_packages_owner_professor_id");

                    b.ToTable("exam_packages", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLogObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("activity_log_object_key");

                    b.Property<string>("ActivityLogSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("activity_log_sha256")
                        .IsFixedLength();

                    b.Property<long>("ActivityLogSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_log_size_bytes");

                    b.Property<Guid>("DeviceCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_credential_id");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id");

                    b.Property<string>("SolutionObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("solution_object_key");

                    b.Property<string>("SolutionSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("solution_sha256")
                        .IsFixedLength();

                    b.Property<long>("SolutionSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("solution_size_bytes");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("ActivityLogObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_activity_log_object_key");

                    b.HasIndex("DeviceCredentialId")
                        .HasDatabaseName("ix_submissions_device_credential_id");

                    b.HasIndex("SolutionObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_solution_object_key");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submissions_student_id");

                    b.HasIndex("ExamSessionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_exam_session_id_student_id");

                    b.ToTable("submissions", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("IndexNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("index_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IndexNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_index_number")
                        .HasFilter("index_number IS NOT NULL");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Web.Api.Features.Devices.DeviceCredential", b =>
                {
                    b.HasOne("Web.Api.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credentials_users_user_id");
                });

            modelBuilder.Entity("Web.Api.Features.ExamSessions.ExamSession", b =>
                {
                    b.HasOne("Web.Api.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_sessions_users_created_by_professor_id");

                    b.HasOne("Web.Api.Features.Exams.ExamPackage", null)
                        .WithMany()
                        .HasForeignKey("ExamPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_sessions_exam_packages_exam_package_id");
                });

            modelBuilder.Entity("Web.Api.Features.Exams.ExamDependency", b =>
                {
                    b.HasOne("Web.Api.Features.Exams.ExamPackage", null)
                        .WithMany()
                        .HasForeignKey("ExamPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_dependencies_exam_packages_exam_package_id");
                });

            modelBuilder.Entity("Web.Api.Features.Exams.ExamFile", b =>
                {
                    b.HasOne("Web.Api.Features.Exams.ExamPackage", null)
                        .WithMany()
                        .HasForeignKey("ExamPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_files_exam_packages_exam_package_id");
                });

            modelBuilder.Entity("Web.Api.Features.Exams.ExamPackage", b =>
                {
                    b.HasOne("Web.Api.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_packages_users_owner_professor_id");
                });

            modelBuilder.Entity("Web.Api.Features.Submissions.Submission", b =>
                {
                    b.HasOne("Web.Api.Features.Devices.DeviceCredential", null)
                        .WithMany()
                        .HasForeignKey("DeviceCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_device_credentials_device_credential_id");

                    b.HasOne("Web.Api.Features.ExamSessions.ExamSession", null)
                        .WithMany()
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_exam_sessions_exam_session_id");

                    b.HasOne("Web.Api.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_users_student_id");
                });

            modelBuilder.Entity("Web.Api.Features.Users.RefreshToken", b =>
                {
                    b.HasOne("Web.Api.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
